services:
  worker:
    image: ghcr.io/shrestha-bishal/sure-sync-worker:latest
    container_name: sure-sync-worker
    user: "0:0"
    env_file:
      - .env
    environment:
      - CONSUME_PATH=/app/consume
      - PROCESSED_DIR=/app/consume/processed
      - FAILED_DIR=/app/consume/failed
    volumes:
      - ${CONSUME_PATH}:/app/consume
      - ${DATA_PATH}:/app/data
    restart: unless-stopped

  web:
    image: ghcr.io/shrestha-bishal/sure-sync-web:latest
    container_name: sure-sync-web
    env_file:
      - .env
    ports:
      - "9000:8000"
    volumes:
      - ${DATA_PATH}:/app/data
    restart: unless-stopped
    depends_on:
      - worker
