services:
  worker:
    build: 
      context: .
      target: worker-stage
    container_name: sure-sync-worker
    #command: python -u app/main.py
    env_file:
      - .env
    volumes:
      - ${CONSUME_PATH}:/app/consume
      - ${CONSUME_PATH}/processed:/app/processed
      - ${STATS_PATH}/stats.json:/app/data/stats.json
      - ./account-mapping.yml:/app/data/account-mapping.yml:ro
    restart: unless-stopped
  
  web:
    build: 
      context: .
      target: web-stage
    container_name: sure-sync-web
    ports:
      - "9000:8000"
    volumes:
      - ${STATS_PATH}/stats.json:/app/data/stats.json
    restart: unless-stopped
    depends_on:
      - worker